site_name: My Docs
site_description: Documentation for My Project
site_author: Your Name

theme:
  name: material

nav:
  - Home: index.md
  - About:
      - Overview: about/overview.md
      - Team: about/team.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Installation: user-guide/installation.md
      - Configuration: user-guide/configuration.md
  - API Reference: api-reference.md
  - FAQ: faq.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - mkdocs-material